# Streamlit Cloud secrets configuration
# Add this file to your repository for automatic deployment

SUPABASE_URL = "https://thvugbyogpuvcljlcplf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRodnVnYnlvZ3B1dmNsamxjcGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjQxODgsImV4cCI6MjA2NTEwMDE4OH0.zM9jr8RXEqTDSjFcFhOVBzpi-iSg8-BkxvdULwqAxww"

# Optional: Add your other API keys
# OPENROUTER_KEY = "your_openrouter_key_here"
TENOR_API_KEY = "AIzaSyAARkiZD-Qo59Pji8ihow4hJCZDOsdchzE"
WEATHER_API_KEY = "24b359c76d994182864153220251507"