# Streamlit Cloud Secrets Configuration
# Add your API keys here for deployment

# Supabase Configuration (Required for mood history)
SUPABASE_URL = "https://grhrzxgxazzvnouxczbb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyaHJ6eGd4YXp6dm5vdXhjemJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTkyNDQsImV4cCI6MjA2NTE5NTI0NH0.9Kk47EZJGDrSGWK5m8ntfmF694Z-EulSjzd7DVvBMw8"

# Weather API (Free tier available)
WEATHER_API_KEY = "24b359c76d994182864153220251507"

# Optional: Add your API keys for enhanced features
# OPENROUTER_KEY = "your_openrouter_key_here"  # For AI therapy chat
# TENOR_API_KEY = "your_tenor_key_here"        # For emotion GIFs